# Generated by Django 2.0.4 on 2018-04-30 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('V', 'Verified'), ('D', 'Done'), ('WG', 'Weekly Goal'), ('DT', 'Daily Task')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.TextField(default='user@scrumyapp', max_length=150)),
                ('role', models.CharField(choices=[('O', 'Owner'), ('A', 'Admin'), ('Q', 'Quality Analyst'), ('D', 'Developer')], default=1, max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugwuezescrumy.ScrumyUser'),
        ),
        migrations.AddField(
            model_name='goalstatus',
            name='goal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugwuezescrumy.ScrumyGoals'),
        ),
        migrations.AddField(
            model_name='goalstatus',
            name='verified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugwuezescrumy.ScrumyUser'),
        ),
    ]
