# Generated by Django 2.0.4 on 2018-04-30 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugwuezescrumy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalstatus',
            name='goal_id',
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='goal_status_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ugwuezescrumy.GoalStatus'),
        ),
        migrations.AlterField(
            model_name='goalstatus',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('V', 'Verified'), ('D', 'Done'), ('WG', 'Weekly Goal'), ('DT', 'Daily Task')], default=1, max_length=1),
        ),
    ]
