# Generated by Django 2.0.4 on 2018-04-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugwuezescrumy', '0002_auto_20180430_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalstatus',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('V', 'Verified'), ('D', 'Done'), ('WG', 'Weekly Goal'), ('DT', 'Daily Task')], max_length=1),
        ),
    ]
