# Generated by Django 2.0.4 on 2018-04-30 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugwuezescrumy', '0003_auto_20180430_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumygoals',
            name='goal_status_id',
        ),
    ]
