# Generated by Django 2.0.4 on 2018-04-30 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugwuezescrumy', '0004_remove_scrumygoals_goal_status_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalstatus',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='goal_status_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ugwuezescrumy.GoalStatus'),
        ),
    ]
