# Generated by Django 2.0.4 on 2018-04-30 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugwuezescrumy', '0005_auto_20180501_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalstatus',
            name='verified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ugwuezescrumy.ScrumyUser'),
        ),
    ]
