# Generated by Django 2.0.4 on 2018-05-01 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugwuezescrumy', '0007_auto_20180501_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_status_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ugwuezescrumy.GoalStatus'),
        ),
    ]
